### ISSUE TITLE
CVPR 2024 latex complate problems on local windows tex live

### ISSUE THREAD

**Issue by LWShowTime** [cvpr-org/author-kit#16]
the citation goes wrong.
![image](https://github.com/cvpr-org/author-kit/assets/51390653/8b1d4f43-3c84-4bd2-856d-12165cb9c07f)
![image](https://github.com/cvpr-org/author-kit/assets/51390653/70ff6102-58ee-42b1-bc6d-73e210a4d093)
However, on Overleaf, everything is ok.

**Comment by cr333** [comment]
This is not a problem with the template.

If you want to manually compile any LaTeX document with BibTeX citations, you will need to call the `latex` and `bibtex` commands in an interleaved fashion:
```
latex main
bibtex main
latex main
latex main
```

### How does this work?
1. The first run of `latex` creates a file `main.aux` that contains the citations found in the document.
2. The next call, to `bibtex`, then reads this in to produce a file `main.bbl` containing the bibliographic information for these citations.
3. The next run of `latex` includes this bibliography information in the document, and makes the warnings you see go away.
4. The final run of `latex` updates page numbers and references that may have changed due to the previous run.

Overleaf and some LaTeX editors, such as [TeXstudio](https://www.texstudio.org/), automatically run all these steps for you.

**Comment by LWShowTime** [comment]
@cr333 
Thank you for your detailed explanation! I follow these four steps and everything is OK on my windows environment now! I highly appreciate your help!
