### ISSUE TITLE
Flushend package does not work

### ISSUE THREAD

**Issue by BjoernMichele** [cvpr-org/author-kit#30]
Thank you very much for this nice looking Template. 

I just realized, that with the CVPR 2024 templace, the 'flushend' package does not work any more (it works with the CPVR 2023 template). The package balances the references on the last page, which looks a bit smoother. 

An alternative for that using the 'adjustbox' package, together with the \balance command, is also not working anymore. 

It is probably not a big issue, but maybe you are aware of a workaround :) 

Best, 
Bjoern

**Comment by taiya** [comment]
I had tried the balance package, but no, not yet.
I'll keep this open and maybe find a workaround for camera ready?

**Comment by BjoernMichele** [comment]
Thanks a lot :)  has the balance package work for you ? As for me it produced a single column reference

**Comment by taiya** [comment]
Not during the deadline, but I haven't tried very hard.

**Comment by cr333** [comment]
The reason why `flushend` no longer worked in the CVPR 2024 template is that we replaced the review line numbering in 4211180 using the `lineno` package, which is [incompatible with with the `flushend` package](https://tex.stackexchange.com/questions/136884/incompatibility-between-flushend-and-lineno-packages).

As a fix, I have wrapped the line numbering code in the paper template in 566fc4b8d90c224039fd9f218f2eedfa66a80484, such that the `flushend` and `pbalance` packages now work as expected for the camera-ready `cvprfinal` version.

Note: the `review` and `rebuttal` versions remain won't support balancing the columns for now, but that does not seem critical. However, we do welcome any fixes from the community.

**Comment by NightMachinery** [comment]
<img width="674" alt="image" src="https://github.com/user-attachments/assets/d09c3b37-3c78-4fd6-a60e-218990487308">

CVPR 2025 V3.1 Template:

In the References section, there's excessive white space in the left column of the first page of references, even though there are more references to display on subsequent pages. Is this expected behavior?

I've already tried:
1. `\raggedbottom` - This only shifts the white space to the bottom of the first column without solving the distribution issue
2. `balance` package with `\balance` before references - No effect
3. `flushend` package - No effect

**Comment by taiya** [comment]
Try to disable clearpage before references (would like a better fix one day)

**Comment by NightMachinery** [comment]
@taiya I don't have `\clearpage`, but I do have `\FloatBarrier` before the bibliography. I need that, as without the barrier, my tables will go in the middle of references.
