### ISSUE TITLE
LaTeX Error: Command \@EveryShipout@Hook already defined.

### ISSUE THREAD

**Issue by nissmar** [cvpr-org/author-kit#41]
Hi, 

I'm trying to use PDF eXpress to generate my files from the template but I keep receiving: 
`LaTeX Error: Command \@EveryShipout@Hook already defined.` 
Do you know what might be the issue? 

Thank you. 
Best, 
Nissim

**Comment by cr333** [comment]
Hey Nissim, which version of the template you are using?

Does the problem persist when using the latest `cvpr.sty` template from this repository?

In case this is caused by a conflict with TikZ, you [can find a solution here](https://tex.stackexchange.com/a/398269).

If all else fails, the submission instructions sound like you can also directly submit a PDF to PDF eXpress.

Please let us know what works for you.

**Comment by nissmar** [comment]
Hey Christian, 
Thank you for your answer, yes I'm using the latest version of the template. 
The TikZ solution did improve the LaTeX error, but I now have "LaTeX Error: Environment pNiceArray undefined" although I did include nicematrix. 
I might directly submit the PDF, thank you for the advice.
